# Generated by Django 6.1.1 on 2026-09-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_data_erased_user_deleted_at_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
