# Generated by Django 6.1.1 on 2026-09-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='mediation.mediation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='mediation.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AI_MEDIATOR', 'AI Mediator'), ('SYSTEM', 'System')], default='USER', max_length=20)),
                ('content', models.TextField()),
                ('message_type', models.CharField(blank=True, default='TEXT', max_length=30)),
                ('risk_flagged', models.BooleanField(default=False)),
                ('risk_categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('mediation', 'participant'), name='unique_participant_conversation'),
        ),
    ]
