# Generated by Django 6.1.1 on 2026-09-12 19:40

import security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=security.fields.EncryptedTextField(),
        ),
    ]
