# Generated by Django 6.1.1 on 2026-09-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediation', '0001_initial'),
        ('resolutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preamble', models.TextField(blank=True, default='')),
                ('agreed_terms', models.JSONField(blank=True, default=list)),
                ('participant_responsibilities', models.JSONField(blank=True, default=dict)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('dispute_escalation_clause', models.TextField(blank=True, default='')),
                ('signatures', models.JSONField(blank=True, default=dict)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mediation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='mediation.mediation')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='resolutions.resolution')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('WORKING', 'Working'), ('PARTIALLY_WORKING', 'Partially Working'), ('NOT_WORKING', 'Not Working')], max_length=24)),
                ('comments', models.TextField(blank=True, default='')),
                ('reopen_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reports', to='mediation.mediation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='mediation.participant')),
            ],
        ),
    ]
