# Generated by Django 6.1.1 on 2026-09-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='document_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
