# Generated by Django 6.1.1 on 2026-09-12 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='General', max_length=60)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('INVITED', 'Invited'), ('IN_PROGRESS', 'In Progress'), ('ANALYZED', 'Analyzed'), ('PROPOSALS_READY', 'Proposals Ready'), ('NEGOTIATING', 'Negotiating'), ('RESOLVED', 'Resolved'), ('FOLLOW_UP', 'Follow Up'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed'), ('SAFETY_HOLD', 'Safety Hold')], default='CREATED', max_length=32)),
                ('invite_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('safety_hold', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mediations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('role', models.CharField(blank=True, default='Participant', max_length=80)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('JOINED', 'Joined'), ('IN_SESSION', 'In Session'), ('SESSION_COMPLETED', 'Session Completed'), ('REVIEWED', 'Reviewed'), ('SIGNED', 'Signed')], default='JOINED', max_length=32)),
                ('consent_given', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('has_completed_private_session', models.BooleanField(default=False)),
                ('mediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='mediation.mediation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('mediation', 'user'), name='unique_mediation_participant')],
            },
        ),
    ]
