# Generated by Django 6.1.1 on 2026-09-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_goals', models.JSONField(blank=True, default=list)),
                ('conflicting_goals', models.JSONField(blank=True, default=list)),
                ('root_causes', models.JSONField(blank=True, default=list)),
                ('misunderstandings', models.JSONField(blank=True, default=list)),
                ('emotional_factors', models.JSONField(blank=True, default=list)),
                ('expectation_gaps', models.JSONField(blank=True, default=list)),
                ('non_negotiable_concerns', models.JSONField(blank=True, default=list)),
                ('potential_compromises', models.JSONField(blank=True, default=list)),
                ('common_ground_summary', models.TextField(blank=True, default='')),
                ('compatibility_score', models.IntegerField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mediation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='mediation.mediation')),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('model_type', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('tradeoffs', models.JSONField(blank=True, default=list)),
                ('required_compromises', models.JSONField(blank=True, default=dict)),
                ('expected_impact', models.TextField(blank=True, default='')),
                ('why_it_works', models.TextField(blank=True, default='')),
                ('refinement_iteration', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='mediation.mediation')),
            ],
            options={
                'ordering': ['proposal_number', '-refinement_iteration', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.JSONField(blank=True, default=list)),
                ('concerns', models.JSONField(blank=True, default=list)),
                ('needs', models.JSONField(blank=True, default=list)),
                ('constraints', models.JSONField(blank=True, default=list)),
                ('emotions', models.JSONField(blank=True, default=list)),
                ('desired_outcome', models.TextField(blank=True, default='')),
                ('acceptable_compromises', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mediation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perspectives', to='mediation.mediation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perspective', to='mediation.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mediation', 'participant'), name='unique_participant_perspective')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPT', 'Accept'), ('REQUEST_CHANGES', 'Request Changes'), ('REJECT', 'Reject')], max_length=24)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='mediation.participant')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='resolutions.resolution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resolution', 'participant'), name='unique_participant_vote')],
            },
        ),
    ]
